### ISSUE TITLE
Crash entering on Albums

### ISSUE THREAD

**Issue by RamXX** [rbackhouse/mpdjs#9]
Hi there. All functions work as expected except for 'Albums'. Selecting Albums crashes the program on Mac (installed via `npm`). Mpd server on Linux 0.19.21.
```
➜  workspace node node_modules/mpdjs 8080 10.74.11.51 6600 false
No password speficied on cmdline
MPD Web Client available on HTTP port [8080] connected to MPD server [10.74.11.51:6600] javascript compression [false] using password []
MPD connection is ready

/Users/ramxx/workspace/node_modules/mpdjs/lib/mpdconnector.js:168
					if (name.trim().length > 0 && album) {
					        ^

TypeError: Cannot read property 'trim' of undefined
    at Object.<anonymous> (/Users/rsalas/workspace/node_modules/mpdjs/lib/mpdconnector.js:168:14)
    at Object.<anonymous> (/Users/rsalas/workspace/node_modules/mpdjs/lib/mpdconnector.js:61:21)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:536:20)
```

**Comment by rbackhouse** [comment]
That error would indicate there is something wrong with an Album tag in one of your files. Perhaps if you can run something like "mpc list album" on your music db to see if anything jumps out.
